# Prepends `features = ["chase-raw-pointers"]` to a config_gen.py-produced
# oid config, since config_gen.py itself has no --features flag. Invoked as
# a build step (`cmake -DIN_FILE=... -DOUT_FILE=... -P
# PrependChaseRawPointersFeature.cmake`) rather than at configure time,
# since IN_FILE is itself generated by an earlier build step.
#
# chase-raw-pointers is on here specifically (not as a project-wide default
# - see docs/object-capture-initial-thoughts.md, not part of this repo)
# because CycleBreakingDemo.cpp's RawNode::next member needs to actually be
# chased to exercise BreakCycles at all - without it, a raw pointer member
# silently degrades to StubbedPointer (an inert captured address, never
# walked into), which would make this demo pass trivially without proving
# anything.
file(READ "${IN_FILE}" _cycle_breaking_demo_config_contents)
file(WRITE "${OUT_FILE}"
  "features = [\"chase-raw-pointers\"]\n${_cycle_breaking_demo_config_contents}"
)
