# Prepends `features = ["capture-bytes", "chase-raw-pointers"]` to a
# config_gen.py-produced oid config, since config_gen.py itself has no
# --features flag. Invoked as a build step (`cmake -DIN_FILE=... -DOUT_FILE=...
# -P PrependCaptureBytesFeature.cmake`) rather than at configure time, since
# IN_FILE is itself generated by an earlier build step.
#
# chase-raw-pointers is on here specifically (not as a project-wide default -
# see docs/object-capture-initial-thoughts.md, not part of this repo) because
# DemoObject has no self-referential types, so it carries none of the
# #293-style build-failure risk a self-referential type would - without it, a
# raw pointer member would silently degrade to StubbedPointer (an inert
# captured address, not a reconstructable pointee).
file(READ "${IN_FILE}" _reconstruct_demo_config_contents)
file(WRITE "${OUT_FILE}"
  "features = [\"capture-bytes\", \"chase-raw-pointers\"]\n${_reconstruct_demo_config_contents}"
)
