# Prepends `features = ["capture-bytes"]` to a config_gen.py-produced oid
# config, since config_gen.py itself has no --features flag. Invoked as a
# build step (`cmake -DIN_FILE=... -DOUT_FILE=... -P
# PrependCaptureBytesFeature.cmake`) rather than at configure time, since
# IN_FILE is itself generated by an earlier build step.
file(READ "${IN_FILE}" _reconstruct_demo_config_contents)
file(WRITE "${OUT_FILE}"
  "features = [\"capture-bytes\"]\n${_reconstruct_demo_config_contents}"
)
