[info]
type_name = "std::array"
ctype = "ARRAY_TYPE"
header = "array"

# Old:
numTemplateParams = 1
ns = ["namespace std"]
typeName = "std::array<"

[codegen]
decl = """
template<typename T, long unsigned int N>
void getSizeType(const %1%<T, N> &container, size_t& returnArg);
"""

func = """
template<typename T, long unsigned int N>
void getSizeType(const %1%<T,N> &container, size_t& returnArg)
{
    SAVE_DATA((uintptr_t)container.size());
    SAVE_SIZE(sizeof(container));

    for (auto & it: container) {
        // undo the static size that has already been added per-element
        SAVE_SIZE(-sizeof(it));
        getSizeType(it, returnArg);
    }
}
"""

traversal_func = """
    auto tail = returnArg.delegate([&container](auto intervals) {
        return intervals.write(1).delegate([&container](auto interval) {
            return interval
                .write(reinterpret_cast<uintptr_t>(&container))
                .write(sizeof(container));
        }).finish();
    }).write(container.size());

    for (auto & it: container) {
        tail = tail.delegate([&ctx, &it](auto ret) {
            return TypeHandler<Ctx, T0>::getSizeType(ctx, it, ret);
        });
    }

    return tail.finish();
"""

[[codegen.processor]]
type = "types::st::List<DB, types::st::Pair<DB, types::st::VarInt<DB>, types::st::VarInt<DB>>>"
func = """
auto list = std::get<ParsedData::List>(d.val);

el.va_intervals.clear();
el.va_intervals.reserve(list.length);

for (size_t i = 0; i < list.length; ++i) {
  auto item = list.values();
  auto pair = std::get<ParsedData::Pair>(item.val);

  auto base = std::get<ParsedData::VarInt>(pair.first().val).value;
  auto size = std::get<ParsedData::VarInt>(pair.second().val).value;

  if (base != 0 && size != 0) {
    el.va_intervals.push_back(result::Element::VAInterval{
        .base = static_cast<uintptr_t>(base),
        .size = static_cast<std::size_t>(size),
    });
  }
}
"""

[[codegen.processor]]
type = "types::st::List<DB, typename TypeHandler<Ctx, T0>::type>"
func = """
static constexpr auto childField = make_field<Ctx, T0>("[]");

size_t size = std::get<ParsedData::List>(d.val).length;
el.exclusive_size = N0 == 0 ? 1 : 0;
el.container_stats.emplace(result::Element::ContainerStats{ .capacity = size, .length = size });
for (size_t i = 0; i < size; i++)
  stack_ins(childField);
"""
