[info]
type_name = "std::__cxx11::list"
stub_template_params = [1]
header = "list"

# Old:
ctype = "LIST_TYPE"
typeName = "std::__cxx11::list"
ns = ["namespace std"]
numTemplateParams = 1
replaceTemplateParamIndex = []
allocatorIndex = 1

[codegen]
decl = """
template<typename T, typename Allocator>
void getSizeType(const %1%<T, Allocator> &container, size_t& returnArg);
"""

func = """
template<typename T, typename Allocator>
void getSizeType(const %1%<T, Allocator> &container, size_t& returnArg)
{
    SAVE_SIZE(sizeof(%1%<T>));

    SAVE_DATA((uintptr_t)&container);
    SAVE_DATA((uintptr_t)container.size());

    // The double ampersand is needed otherwise this loop doesn't work with vector<bool>
    for (auto&& it: container) {
    getSizeType(it, returnArg);
    }
}
"""

traversal_func = """
auto tail = returnArg.delegate([&container](auto intervals) {
#ifdef __GLIBCXX__
  auto contents = intervals.write(container.size() + 1);

  contents = contents.delegate([&container](auto interval) {
    return interval
        .write(reinterpret_cast<uintptr_t>(&container))
        .write(sizeof(container));
  });

  for (auto it = container.begin(); it != container.end(); ++it) {
    const auto* node = static_cast<const std::_List_node<T0>*>(it._M_node);

    contents = contents.delegate([node](auto interval) {
      return interval
          .write(reinterpret_cast<uintptr_t>(node))
          .write(sizeof(*node));
    });
  }

  return contents.finish();
#else
  static_assert(false && "No known list node layout. See types/cxx11_list_type.toml");
#endif
})
                .write((uintptr_t)&container)
                .write(container.size());

for (auto&& it : container) {
  tail = tail.delegate([&ctx, &it](auto ret) {
    return OIInternal::getSizeType<Ctx>(ctx, it, ret);
  });
}

return tail.finish();
"""

[[codegen.processor]]
type = "types::st::List<DB, types::st::Pair<DB, types::st::VarInt<DB>, types::st::VarInt<DB>>>"
func = """
auto list = std::get<ParsedData::List>(d.val);

el.va_intervals.clear();
el.va_intervals.reserve(list.length);

for (size_t i = 0; i < list.length; ++i) {
  auto item = list.values();
  auto pair = std::get<ParsedData::Pair>(item.val);

  auto base = std::get<ParsedData::VarInt>(pair.first().val).value;
  auto size = std::get<ParsedData::VarInt>(pair.second().val).value;

  if (base != 0 && size != 0) {
    el.va_intervals.push_back(result::Element::VAInterval{
        .base = static_cast<uintptr_t>(base),
        .size = static_cast<std::size_t>(size),
    });
  }
}
"""

[[codegen.processor]]
type = "types::st::VarInt<DB>"
func = """
el.pointer = std::get<ParsedData::VarInt>(d.val).value;
"""

[[codegen.processor]]
type = "types::st::List<DB, typename TypeHandler<Ctx, T0>::type>"
func = """
#ifdef __GLIBCXX__
static constexpr size_t element_size = sizeof(std::_List_node<T0>);
#else
static_assert(false && "No known element_size for list. See types/cxx11_list_type.toml");
#endif

static constexpr auto childField = make_field<Ctx, T0>("[]");

auto list = std::get<ParsedData::List>(d.val);
el.container_stats.emplace(result::Element::ContainerStats{
  .capacity = list.length,
  .length = list.length,
});
el.exclusive_size += el.container_stats->length * (element_size - sizeof(T0));

stack_ins(inst::Repeat{ list.length, childField });
"""
